# ============================================================
# PHI Identification Prompt Configuration
# PHI 識別 Prompt 配置
# ============================================================
# Version: 1.0.0
# Last Updated: 2024-12-30
# Optimized For: granite4:1b, qwen2.5:1.5b
# ============================================================

metadata:
  name: phi_identification
  version: "1.0.0"
  description: |
    識別醫療文本中的個人健康資訊 (PHI)
    Identify Protected Health Information (PHI) in medical text
  author: Medical De-identification Team
  created_at: "2024-12-30"
  updated_at: "2024-12-30"
  
  # Benchmark performance
  benchmark:
    model: granite4:1b
    f1_score: 0.894
    avg_time_ms: 15770
    test_cases: 4

# ============================================================
# PHI Type Definitions
# ============================================================
phi_types:
  # Identity
  NAME:
    description: 病患姓名、醫師姓名、家屬姓名
    examples:
      - 王大明
      - Dr. John Smith
      - 病患家屬李小姐
    regex_patterns:
      - "[\\u4e00-\\u9fa5]{2,4}"  # Chinese names
      - "Dr\\.?\\s*[A-Z][a-z]+"   # Dr. prefix
    priority: high
    
  ID:
    description: 身分證號、醫療病歷號、健保卡號
    examples:
      - A123456789
      - "MRN: 12345678"
      - 健保卡號 000012345678
    regex_patterns:
      - "[A-Z][12]\\d{8}"  # Taiwan ID
      - "\\d{8,12}"        # MRN
    priority: critical
    
  SSN:
    description: 社會安全碼（美國）
    examples:
      - 123-45-6789
    regex_patterns:
      - "\\d{3}-\\d{2}-\\d{4}"
    priority: critical

  # Contact
  PHONE:
    description: 電話號碼、手機號碼、傳真
    examples:
      - 0912-345-678
      - (02) 2345-6789
      - 傳真 02-12345678
    regex_patterns:
      - "09\\d{2}[-\\s]?\\d{3}[-\\s]?\\d{3}"
      - "\\(0\\d\\)\\s*\\d{4}[-\\s]?\\d{4}"
    priority: high
    
  EMAIL:
    description: 電子郵件地址
    examples:
      - patient@example.com
    regex_patterns:
      - "[\\w.-]+@[\\w.-]+\\.\\w+"
    priority: high
    
  FAX:
    description: 傳真號碼
    examples:
      - Fax: 02-12345678
    regex_patterns:
      - "(?:Fax|傳真)[:\\s]*[\\d-]+"
    priority: medium

  # Location
  LOCATION:
    description: 地址、城市（小於州級）
    examples:
      - 台北市信義區市府路1號
      - 新竹科學園區
    regex_patterns:
      - "[\\u4e00-\\u9fa5]+[市縣][\\u4e00-\\u9fa5]+[區鄉鎮]"
    priority: high
    
  ADDRESS:
    description: 完整地址
    examples:
      - 100 台北市中正區忠孝東路一段1號
    regex_patterns:
      - "\\d{3}\\s*[\\u4e00-\\u9fa5]+"
    priority: high

  # Date & Age
  DATE:
    description: 日期（生日、入院日、手術日等）
    examples:
      - 2024-01-15
      - 113年5月20日
      - 1990/03/25
    regex_patterns:
      - "\\d{4}[-/]\\d{1,2}[-/]\\d{1,2}"
      - "\\d{2,3}年\\d{1,2}月\\d{1,2}日"
    priority: high
    
  AGE:
    description: 年齡（特別注意 89 歲以上）
    examples:
      - 45歲
      - 92 years old
    regex_patterns:
      - "\\d{1,3}\\s*[歲岁]"
      - "\\d{1,3}\\s*years?\\s*old"
    special_rule: "AGE_OVER_89 需特別標記"
    priority: medium
    
  AGE_OVER_89:
    description: 89歲以上（HIPAA 特殊處理）
    examples:
      - 92歲
      - 95 years old
    priority: critical

  # Medical
  FACILITY:
    description: 醫院名稱、診所名稱
    examples:
      - 台北榮民總醫院
      - 長庚醫院
    regex_patterns:
      - "[\\u4e00-\\u9fa5]+[醫院診所]"
    priority: medium
    
  MRN:
    description: 病歷號碼
    examples:
      - "病歷號: A12345678"
    regex_patterns:
      - "病歷號[：:]?\\s*[A-Z]?\\d+"
    priority: critical
    
  DEVICE_ID:
    description: 醫療設備序號
    examples:
      - "Pacemaker SN: ABC123456"
    priority: medium

  # Other
  URL:
    description: 網址
    examples:
      - https://hospital.com/patient/123
    regex_patterns:
      - "https?://[\\w./\\-?=&]+"
    priority: low
    
  IP_ADDRESS:
    description: IP 位址
    examples:
      - 192.168.1.100
    regex_patterns:
      - "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"
    priority: low
    
  VEHICLE:
    description: 車牌號碼
    examples:
      - ABC-1234
    regex_patterns:
      - "[A-Z]{2,3}-\\d{4}"
    priority: low

# ============================================================
# Prompt Templates
# ============================================================
prompts:
  # Main system prompt
  system:
    template: |
      你是一個專業的醫療 PHI (Personal Health Information) 識別專家。
      你的任務是從醫療文本中精確識別所有個人健康資訊。
      
      ## PHI 類型定義
      
      {% for type_name, type_info in phi_types.items() %}
      - **{{ type_name }}**: {{ type_info.description }}
        範例: {{ type_info.examples | join(', ') }}
      {% endfor %}
      
      ## 輸出格式
      
      請以 JSON 陣列格式輸出，每個 PHI 實體包含：
      - text: 原始文字
      - phi_type: PHI 類型（必須是上述定義的類型之一）
      - reason: 識別原因（簡短說明）
      
      ## 重要規則
      
      1. 只識別真正的 PHI，不要過度標記
      2. 醫師姓名、醫院名稱也是 PHI
      3. 年齡只在 89 歲以上時才標記
      4. 常見疾病名稱（如糖尿病）不是 PHI
      5. 不確定時寧可不標記
    
    variables:
      - phi_types
      
  # User prompt template
  user:
    template: |
      請識別以下醫療文本中的所有 PHI：
      
      ---
      {{ medical_text }}
      ---
      
      以 JSON 陣列格式輸出所有識別到的 PHI。如果沒有找到任何 PHI，請輸出空陣列 []。
    
    variables:
      - medical_text

  # Simplified prompt (for faster inference)
  simplified:
    template: |
      識別醫療文本中的 PHI (姓名、身分證、電話、地址、日期、醫院等)。
      以 JSON 格式輸出: [{"text": "...", "phi_type": "NAME|ID|PHONE|...", "reason": "..."}]
      
      文本：{{ medical_text }}
      
      PHI：
    variables:
      - medical_text

  # Chain-of-thought prompt
  cot:
    template: |
      請逐步分析以下醫療文本，識別所有 PHI：
      
      文本：{{ medical_text }}
      
      分析步驟：
      1. 首先找出所有人名（病患、醫師、家屬）
      2. 接著找出身份識別資訊（身分證、病歷號）
      3. 然後找出聯絡資訊（電話、地址、email）
      4. 最後找出日期和其他 PHI
      
      詳細分析：
    variables:
      - medical_text

# ============================================================
# Few-Shot Examples
# ============================================================
few_shot_examples:
  - input: |
      病患王大明，男性，65歲，身分證字號A123456789。
      聯絡電話：0912-345-678。
      地址：台北市信義區市府路45號。
    output: |
      [
        {"text": "王大明", "phi_type": "NAME", "reason": "病患姓名"},
        {"text": "A123456789", "phi_type": "ID", "reason": "身分證字號"},
        {"text": "0912-345-678", "phi_type": "PHONE", "reason": "聯絡電話"},
        {"text": "台北市信義區市府路45號", "phi_type": "ADDRESS", "reason": "住址"}
      ]
    note: "標準案例，包含姓名、身分證、電話、地址。注意65歲不需標記。"
    
  - input: |
      主治醫師：張明華 醫師
      入院日期：2024年5月15日
      診斷：第二型糖尿病
    output: |
      [
        {"text": "張明華", "phi_type": "NAME", "reason": "醫師姓名"},
        {"text": "2024年5月15日", "phi_type": "DATE", "reason": "入院日期"}
      ]
    note: "醫師姓名是 PHI，糖尿病是疾病名稱不是 PHI。"
    
  - input: |
      92歲女性，於台北榮民總醫院急診就醫。
      病歷號：A00123456
    output: |
      [
        {"text": "92歲", "phi_type": "AGE_OVER_89", "reason": "年齡超過89歲"},
        {"text": "台北榮民總醫院", "phi_type": "FACILITY", "reason": "醫院名稱"},
        {"text": "A00123456", "phi_type": "MRN", "reason": "病歷號碼"}
      ]
    note: "92歲需標記為 AGE_OVER_89，醫院名稱需標記。"

  - input: |
      家屬王先生聯絡方式：
      手機：0987-654-321
      Email: wang@gmail.com
    output: |
      [
        {"text": "王先生", "phi_type": "NAME", "reason": "家屬姓名"},
        {"text": "0987-654-321", "phi_type": "PHONE", "reason": "手機號碼"},
        {"text": "wang@gmail.com", "phi_type": "EMAIL", "reason": "電子郵件"}
      ]
    note: "家屬姓名也是 PHI。"

# ============================================================
# Optimization Settings
# ============================================================
optimization:
  # DSPy optimization settings
  dspy:
    default_method: bootstrap_fewshot
    
    bootstrap_fewshot:
      max_bootstrapped_demos: 3
      max_labeled_demos: 3
      max_rounds: 1
      
    mipro:
      num_candidates: 10
      init_temperature: 1.0
      
  # Target metrics
  targets:
    min_f1_score: 0.80
    max_response_time_ms: 5000
    max_prompt_tokens: 1500
    
  # Weight for combined score
  weights:
    f1_score: 0.70
    time_factor: 0.15
    prompt_factor: 0.15

# ============================================================
# Model-Specific Configurations
# ============================================================
model_configs:
  granite4:1b:
    prompt_style: simplified
    temperature: 0.1
    max_tokens: 1024
    use_cot: false
    notes: "Best for JSON output, use simplified prompt"
    
  qwen2.5:1.5b:
    prompt_style: simplified
    temperature: 0.1
    max_tokens: 1024
    use_cot: false
    notes: "Good balance of speed and quality"
    
  llama3.2:1b:
    prompt_style: cot
    temperature: 0.2
    max_tokens: 1500
    use_cot: true
    notes: "Benefits from chain-of-thought reasoning"
    
  gpt-4o-mini:
    prompt_style: system
    temperature: 0.1
    max_tokens: 2048
    use_cot: false
    notes: "Can handle full system prompt"
